In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv(r"swiggy_raw_dataset.csv")
df.head()

,order_id,customer_id,city,restaurant,cuisine,order_amount,delivery_time_mins,rating,order_status,payment_mode,order_date
0,40,1474,Mumbai,Biryani House,North Indian,709.13,28,4.7,Pending,Wallet,2024-01-04
1,1603,1936,Bangalore,Spice Hub,North Indian,938.23,40,3.6,Pending,Wallet,2024-02-02
2,3344,1252,Mumbai,Pizza World,Desserts,470.62,43,4.7,Cancelled,UPI,2024-01-17
3,4549,1419,Mumbai,Biryani House,Desserts,1448.17,23,4.2,Pending,Wallet,2024-04-22
4,3610,1630,Hyderabad,Urban Tadka,NaN,567.30,10,3.4,Delivered,Wallet,2024-09-05

In [3]:
df.columns

Index(['order_id', 'customer_id', 'city', 'restaurant', 'cuisine',
       'order_amount', 'delivery_time_mins', 'rating', 'order_status',
       'payment_mode', 'order_date'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            5250 non-null   int64
 1   customer_id         5250 non-null   int64
 2   city                4992 non-null   str
 3   restaurant          4988 non-null   str
 4   cuisine             4991 non-null   str
 5   order_amount        5250 non-null   float64
 6   delivery_time_mins  5250 non-null   int64
 7   rating              4986 non-null   float64
 8   order_status        5250 non-null   str
 9   payment_mode        5250 non-null   str
 10  order_date          5250 non-null   str
dtypes: float64(2), int64(3), str(6)
memory usage: 451.3 KB

In [6]:
df.describe()

          order_id  customer_id  order_amount  delivery_time_mins       rating
count  5250.000000  5250.000000   5250.000000         5250.000000  4986.000000
mean   2494.941143  1504.372381    794.791499           34.502857     3.028480
std    1441.934066   290.877086    399.082584           14.328870     1.152456
min       1.000000  1000.000000    100.170000           10.000000     1.000000
25%    1247.250000  1252.000000    449.470000           22.000000     2.000000
50%    2492.500000  1507.000000    792.295000           35.000000     3.000000
75%    3738.750000  1760.000000   1127.415000           47.000000     4.000000
max    5000.000000  1999.000000   1499.850000           59.000000     5.000000

In [7]:
df.isnull().sum()

order_id                0
customer_id             0
city                  258
restaurant            262
cuisine               259
order_amount            0
delivery_time_mins      0
rating                264
order_status            0
payment_mode            0
order_date              0
dtype: int64

In [10]:
df["order_id"].duplicated().sum()

np.int64(250)

In [13]:
df["city"].unique()

<StringArray>
['Mumbai', 'Bangalore', 'Hyderabad', 'Kolkata', 'Delhi', 'Chennai', nan]
Length: 7, dtype: str

In [14]:
df["payment_mode"].unique()

<StringArray>
['Wallet', 'UPI', 'Card', 'Cash']
Length: 4, dtype: str

In [15]:
df["cuisine"].unique()

<StringArray>
['North Indian',     'Desserts',            nan,      'Italian',
 'South Indian',      'Chinese',    'Fast Food']
Length: 7, dtype: str

In [16]:
df["restaurant"].unique()

<StringArray>
['Biryani House',     'Spice Hub',   'Pizza World',   'Urban Tadka',
 'Foodies Point',     'Sushi Zen',             nan]
Length: 7, dtype: str

In [17]:
df["order_status"].unique()

<StringArray>
['Pending', 'Cancelled', 'Delivered']
Length: 3, dtype: str